/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admins;

/**
 *
 * @author Mlkoc
 */
public class a_info extends javax.swing.JFrame {

    /**
     * Creates new form a_driver
     */
    public a_info() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Program Hakkında");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Program Hakkında"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("<html>Lojistik Destek Merkezi Otomasyonu ile şirketinizin tüm işlemlerini tek bir yerden kontrol edebileceksiniz. <br/> Müşterileriniz, şoför bilgilerinizi ve şirketinizin sahip olduğu tır ve kamyonları sisteme kayıt ederek, nakliye işlerinizi takip edebilir,<br/> yeni nakliye kayıtları oluşturabilirsiniz. <br/><br/> Müşterilerinize sistem üzerinden mesaj gönderebilir ve müşterilerinizin yolladığı mesajları görüntüleyebilirsiniz. <br/><br/> Önceki nakliyelerinize ait raporlara ulaşabilir ve gelir-gider bilgilerinizi rahatlıkla görüntüleyebilirsiniz. <br/><br/> Ayrıca Java tabanlı hazırlanan program ile tüm işlemciler üzerinde sorunsuz şekilde programımızı çalıştırabilirsiniz. <br/><br/> ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 27, -1, -1));
        jLabel1.getAccessibleContext().setAccessibleName("artık şirketinizin tüm işlemlerini tek bir yerden kontrol edebileceksiniz. Müşterileriniz, şoför bilgilerinizi ve şirketinizin sahip olduğu tır ve kamyonları sisteme kayıt ederek, nakliye işlerinizi takip edebilir, yeni nakliye kayıtları oluşturabilirsiniz.  Müşterilerinize sistem üzerinden mesaj gönderebilir ve müşterilerinizin yolladığı mesajları görüntüleyebilirsiniz.  Önceki nakliyelerinize ait raporlara ulaşabilir ve gelir-gider bilgilerinizi rahatlıkla görüntüleyebilirsiniz.  Ayrıca Java tabanlı hazırlanan program ile tüm işlemciler üzerinde sorunsuz şekilde programımızı çalıştırabilirsiniz.  Program Yapımcıları: Furkan Belikırık - Göksel Özardalı");
        jLabel1.getAccessibleContext().setAccessibleDescription("");

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 625, 170));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/koc_sistem.PNG"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(a_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(a_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(a_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(a_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new a_info().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
