/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ana_menu;

import admins.a_cargoadd;
import admins.a_client;
import admins.a_drivers;
import admins.a_info;
import admins.a_message;
import admins.a_odemeler;
import admins.a_report;
import admins.a_settings;
import admins.a_truck;

/**
 *
 * @author Mlkoc
 */
public class a_index extends javax.swing.JFrame {

    /**
     * Creates new form a_index
     */
    public a_index() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        aracbtn = new javax.swing.JButton();
        musteribtn = new javax.swing.JButton();
        soforbtn = new javax.swing.JButton();
        nakliyekayitbtn = new javax.swing.JButton();
        ayarbtn = new javax.swing.JButton();
        raporbtn = new javax.swing.JButton();
        messagebtn = new javax.swing.JButton();
        messagebtn1 = new javax.swing.JButton();
        odemeler = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Yönetim Sistemi Anasayfa");
        setMinimumSize(new java.awt.Dimension(760, 465));
        setPreferredSize(new java.awt.Dimension(760, 465));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Ubuntu Mono", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("YÖNETİM ALANI");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 260, 31));

        aracbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        aracbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nakliye/iconpack/64/truck.png"))); // NOI18N
        aracbtn.setText("ARAÇLAR");
        aracbtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        aracbtn.setBorderPainted(false);
        aracbtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        aracbtn.setOpaque(false);
        aracbtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        aracbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aracbtnActionPerformed(evt);
            }
        });
        getContentPane().add(aracbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 10, 80, 84));

        musteribtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        musteribtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nakliye/iconpack/64/relationship.png"))); // NOI18N
        musteribtn.setText("MÜŞTERİLER");
        musteribtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        musteribtn.setBorderPainted(false);
        musteribtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        musteribtn.setOpaque(false);
        musteribtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        musteribtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                musteribtnActionPerformed(evt);
            }
        });
        getContentPane().add(musteribtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 110, 84));

        soforbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        soforbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nakliye/iconpack/64/Man.png"))); // NOI18N
        soforbtn.setText("ŞOFÖRLER");
        soforbtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        soforbtn.setBorderPainted(false);
        soforbtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        soforbtn.setOpaque(false);
        soforbtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        soforbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soforbtnActionPerformed(evt);
            }
        });
        getContentPane().add(soforbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 120, 100, 84));

        nakliyekayitbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nakliyekayitbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nakliye/iconpack/64/Schedule.png"))); // NOI18N
        nakliyekayitbtn.setText("YENİ NAKLİYE KAYIT");
        nakliyekayitbtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        nakliyekayitbtn.setBorderPainted(false);
        nakliyekayitbtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        nakliyekayitbtn.setOpaque(false);
        nakliyekayitbtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        nakliyekayitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nakliyekayitbtnActionPerformed(evt);
            }
        });
        getContentPane().add(nakliyekayitbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, 170, 84));

        ayarbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ayarbtn.setForeground(new java.awt.Color(255, 255, 255));
        ayarbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nakliye/iconpack/64/configure.png"))); // NOI18N
        ayarbtn.setText("İŞLEM AYARLARI");
        ayarbtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ayarbtn.setBorderPainted(false);
        ayarbtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ayarbtn.setOpaque(false);
        ayarbtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ayarbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ayarbtnActionPerformed(evt);
            }
        });
        getContentPane().add(ayarbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, 130, 84));

        raporbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        raporbtn.setForeground(new java.awt.Color(255, 255, 255));
        raporbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nakliye/iconpack/64/chart.png"))); // NOI18N
        raporbtn.setText("RAPORLAR");
        raporbtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        raporbtn.setBorderPainted(false);
        raporbtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        raporbtn.setOpaque(false);
        raporbtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        raporbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                raporbtnActionPerformed(evt);
            }
        });
        getContentPane().add(raporbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 300, 110, 84));

        messagebtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        messagebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nakliye/iconpack/64/Mail-search.png"))); // NOI18N
        messagebtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        messagebtn.setBorderPainted(false);
        messagebtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        messagebtn.setLabel("MESAJLAR");
        messagebtn.setOpaque(false);
        messagebtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        messagebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                messagebtnActionPerformed(evt);
            }
        });
        getContentPane().add(messagebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 120, 90, 84));

        messagebtn1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        messagebtn1.setForeground(new java.awt.Color(255, 255, 255));
        messagebtn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nakliye/iconpack/64/@.png"))); // NOI18N
        messagebtn1.setText("HAKKINDA");
        messagebtn1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        messagebtn1.setBorderPainted(false);
        messagebtn1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        messagebtn1.setOpaque(false);
        messagebtn1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        messagebtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                messagebtn1ActionPerformed(evt);
            }
        });
        getContentPane().add(messagebtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 330, 100, 84));

        odemeler.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        odemeler.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nakliye/iconpack/64/Sales-by-payment-method.png"))); // NOI18N
        odemeler.setText("ÖDEME");
        odemeler.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        odemeler.setBorderPainted(false);
        odemeler.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        odemeler.setOpaque(false);
        odemeler.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        odemeler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                odemelerActionPerformed(evt);
            }
        });
        getContentPane().add(odemeler, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, 110, 84));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Nakliye_Araci_Kredileri.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -70, 770, 490));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void odemelerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_odemelerActionPerformed
        a_odemeler a_odemeler = new a_odemeler();
        this.setVisible(false);
        a_odemeler.setVisible(true);
    }//GEN-LAST:event_odemelerActionPerformed

    private void messagebtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_messagebtn1ActionPerformed
        a_info a_info = new a_info();

        a_info.setVisible(true);
    }//GEN-LAST:event_messagebtn1ActionPerformed

    private void messagebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_messagebtnActionPerformed
        a_message a_message = new a_message();
        this.setVisible(false);
        a_message.setVisible(true);

    }//GEN-LAST:event_messagebtnActionPerformed

    private void raporbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_raporbtnActionPerformed
        a_report a_report = new a_report();
        this.setVisible(false);
        a_report.setVisible(true);
    }//GEN-LAST:event_raporbtnActionPerformed

    private void ayarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ayarbtnActionPerformed
        a_settings a_settings = new a_settings();
        this.setVisible(false);
        a_settings.setVisible(true);
    }//GEN-LAST:event_ayarbtnActionPerformed

    private void nakliyekayitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nakliyekayitbtnActionPerformed
        a_cargoadd a_cargoadd = new a_cargoadd();

        a_cargoadd.setVisible(true);
    }//GEN-LAST:event_nakliyekayitbtnActionPerformed

    private void soforbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soforbtnActionPerformed
        a_drivers a_driver = new a_drivers();
        this.setVisible(false);
        a_driver.setVisible(true);
    }//GEN-LAST:event_soforbtnActionPerformed

    private void musteribtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_musteribtnActionPerformed

        a_client a_client = new a_client();
        this.setVisible(false);
        a_client.setVisible(true);
    }//GEN-LAST:event_musteribtnActionPerformed

    private void aracbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aracbtnActionPerformed
        a_truck a_truck = new a_truck();
        this.setVisible(false);
        a_truck.setVisible(true);
    }//GEN-LAST:event_aracbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(a_index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(a_index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(a_index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(a_index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new a_index().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aracbtn;
    private javax.swing.JButton ayarbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton messagebtn;
    private javax.swing.JButton messagebtn1;
    private javax.swing.JButton musteribtn;
    private javax.swing.JButton nakliyekayitbtn;
    private javax.swing.JButton odemeler;
    private javax.swing.JButton raporbtn;
    private javax.swing.JButton soforbtn;
    // End of variables declaration//GEN-END:variables
}
